import{S as m,i as c}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery"),l=document.querySelector(".searchform"),h=document.querySelector(".search-form"),i=document.querySelector(".animate");i.style.visibility="hidden";const y="https://pixabay.com/api/";let d=new m(".gallery a",{captionDelay:250,captionsData:"alt",close:!0,className:"modal-style"});d.on("show.simplelightbox",function(){});let f=new URLSearchParams({key:"41618210-7d4eb9e03ab25b6c1f3452a1d",q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"});h.addEventListener("submit",o=>{o.preventDefault(),l.value.trim().length!==0&&(v(),p(),f.set("q",l.value),g(),l.value="")});function g(){const o=`${y}?${f}`;p(),fetch(o).then(r=>{if(!r.ok)throw new Error("error");return r.json()}).then(({hits:r})=>{r.length===0&&c.error({title:"Error",position:"topCenter",message:"Sorry, there are no images matching your search query. Please try again!"});let n=r.reduce((s,e)=>s+` <li class="gallery-item">
                            <a class="gallery-link" href="${e.largeImageURL}">
                            <img class="gallery-image" data-source=${e.largeImageURL} src=${e.webformatURL} alt = ${e.tags} width="360" height="200"/>
                            </a>
                            <div class= 'title'>
                            <p>Likes:<span class="value">${e.likes}</p>
                            <p>Views:<span class="value">${e.views}</span></p>
                            <p>Comments:<span class="value">${e.comments}</span></p>
                            <p>Downloads:<span class="value">${e.downloads}</span></p>
                            </div>
                       </li>`,"");u.innerHTML=n,d.refresh(),L()}).catch(()=>{c.error({title:"Error",position:"topCenter",message:"Exeptional error!"})})}function v(){u.replaceChildren()}function L(){i.style.visibility="hidden"}function p(){i.style.visibility="visible"}
//# sourceMappingURL=commonHelpers.js.map
